-- ==========================================
-- Data Masking & RBAC via Secure Views
-- ==========================================
USE DATABASE AEGIS_DB;
USE SCHEMA AEGIS_CORE;

-- 1. Revoke direct table access to enforce zero-trust architecture
REVOKE SELECT ON TABLE AEGIS_DB.AEGIS_CORE.STABLECOIN_TRANSFERS FROM ROLE COMPLIANCE_OFFICER;
REVOKE SELECT ON TABLE AEGIS_DB.AEGIS_CORE.STABLECOIN_TRANSFERS FROM ROLE DATA_ENGINEER;

-- 2. Create a SECURE VIEW to encapsulate dynamic masking logic at the query layer
CREATE OR REPLACE SECURE VIEW AEGIS_DB.AEGIS_CORE.VW_STABLECOIN_TRANSFERS_SECURE AS
SELECT 
    TX_ID,
    TIMESTAMP,
    CASE 
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN SENDER_WALLET
        ELSE '***MASKED_WALLET***' 
    END AS SENDER_WALLET,
    
    CASE 
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN RECEIVER_WALLET
        ELSE '***MASKED_WALLET***' 
    END AS RECEIVER_WALLET,
    
    CASE 
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN AMOUNT_USDC
        ELSE 0.000000 
    END AS AMOUNT_USDC,
    
    RISK_SCORE
FROM AEGIS_DB.AEGIS_CORE.STABLECOIN_TRANSFERS;

-- 3. Grant SELECT privileges on the Secure View to designated roles
GRANT SELECT ON VIEW AEGIS_DB.AEGIS_CORE.VW_STABLECOIN_TRANSFERS_SECURE TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON VIEW AEGIS_DB.AEGIS_CORE.VW_STABLECOIN_TRANSFERS_SECURE TO ROLE DATA_ENGINEER;

SELECT 'Secure View masking deployment completed successfully.' AS STATUS;